task:
  name: CI
  allow_manual_trigger: true
#  trigger:
#    cron: "0,10,20,30,40,50 * * * *"

  container:
    #image: node:20
    #cpu: 1
    #memory: 2G
    image: ghcr.io/puppeteer/puppeteer:latest
    cpu: 2
    memory: 4G
    
  env:
    PUPPETEER_CACHE_DIR: $CIRRUS_WORKING_DIR/.cache/puppeteer
    CF_API_URL: "ENCRYPTED[1f275076ca9517c74bb796d31b213a919f4872c0d13495c7bf3282882b0c0231b155dc464fdf55a062c1b2a8dea276d8]"
    MAIN: "ENCRYPTED[0754a2039228f49879374e6a2822d154afdd98cd355079e43519072d79e78a5c36f8e8c255ed700ed2b5d8061d8745df]"
#    RELEASE: ENCRYPTED[xxx]
#    GITHUB_TOKEN: ENCRYPTED[xxx]
#    CF_API_KEY: ENCRYPTED[xxx]
#    NODE_NAME: ENCRYPTED[xxx]

  # 统一缓存到当前目录下的 .cache 和 node_modules
  all_cache:
    folders:
      - .cache
      - node_modules
      - resource_cache
#      - release_tracking_cache
    #fingerprint_key: v2-all-cache
    fingerprint_key: v3-puppeteer-cache
    reupload_on_changes: true

  setup_script:
    #ln: failed to create symbolic link '/usr/bin/google-chrome': Permission denied
    #- ln -sf /usr/bin/google-chrome-stable /usr/bin/google-chrome
    - mkdir -p .cache/fonts
    - |
      if [ ! -f ".cache/fonts/.fonts_installed" ]; then
        echo "检测到字体缓存缺失，开始安装..."
        apt-get update -qq && apt-get install -y fonts-wqy-microhei fonts-noto-cjk
        # 将安装的字体复制到缓存目录以便下次使用
        cp -r /usr/share/fonts/truetype/wqy/* .cache/fonts/ 2>/dev/null || true
        cp -r /usr/share/fonts/opentype/noto/* .cache/fonts/ 2>/dev/null || true
        touch .cache/fonts/.fonts_installed
      else
        echo "利用缓存字体..."
        # 将缓存的字体链接回系统字体目录（或直接使用 fc-cache 扫描缓存目录）
        mkdir -p /usr/share/fonts/truetype/wqy
        mkdir -p /usr/share/fonts/opentype/noto
        cp .cache/fonts/* /usr/share/fonts/truetype/wqy/ 2>/dev/null || true
        # 刷新字体缓存
        fc-cache -fv
      fi
    #检测到字体缓存缺失，开始安装...
    #E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
    #E: Unable to lock directory /var/lib/apt/lists/
 
  install_script:
    # 安装依赖，利用缓存后此步骤仅在 package 变化或缓存丢失时执行
    - npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-adblocker croner @octokit/rest axios fs-extra

  run_script:
    - mkdir -p resource_cache
    - find . -name google-chrome
    - find . -name google-chrome-stable
    #- printenv MAIN > main2.js
    #- cat main2.js 
    #- node -e 'require("fs").writeFileSync("main.js", process.env.MAIN)'
    - node -e "require('fs').writeFileSync('main.js', Buffer.from(process.env.MAIN, 'base64').toString('utf8'))"
    #- cat main.js 
    - node main.js
    - find . -name resource_cache
    - find . -name node_modules