container:
  image: node:20

monitor_task:
  env:
    # 强制 Puppeteer 缓存到当前目录
    PUPPETEER_CACHE_DIR: $CIRRUS_WORKING_DIR/.cache/puppeteer
    CF_API_URL: ENCRYPTED[!3bab141ad9bcf5143bb1bf072f0945bcd9032c0c4877feac224bb08504d42ae06f95719f6bae32f619f7866b93c79bf0!]
    MAIN: ENCRYPTED[!9807ff12e0cae55741571816771ebc011c494a61ca5cde6845c97761a2858983a246e8d28625e412c452529a1ade3029!]
    #ENCRYPTED[!afd37645287da288fe22200c35dc83fa6970c0130594b3d01877689f039738f4fbebe6da2dafb5de91dee633151adc04!]
    #ENCRYPTED[!12336b1e63fb0f496c6fe7afc6fee12e2fba0c28c4e3017d4eb8caa0103dcb8c6cca94b95389328b2d95df02f394ee00!]旧版
#    RELEASE: ENCRYPTED[xxx]
#    GITHUB_TOKEN: ENCRYPTED[xxx]
#    CF_API_KEY: ENCRYPTED[xxx]
#    NODE_NAME: ENCRYPTED[xxx]

  # 统一缓存到当前目录下的 .cache 和 node_modules
  all_cache:
    folders:
      - .cache
      - node_modules
      - release_tracking_cache
      - resource_cache
    fingerprint_key: v2-all-cache
    reupload_on_changes: true

  setup_script:
    # 准备字体目录并建立软链接
    - mkdir -p .cache/fonts ~/.local/share
    - ln -sf $CIRRUS_WORKING_DIR/.cache/fonts ~/.local/share/fonts
    # 安装字体和依赖
    - apt-get update -qq && apt-get install -y fonts-wqy-microhei fonts-noto-cjk
    - fc-cache -fv
    - npm install puppeteer-core puppeteer-extra puppeteer-extra-plugin-adblocker croner @octokit/rest axios fs-extra

  run_script:
    - printf "%s" "$MAIN" > main.js
    - node main.js